### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DaNeo61** [v10networkscom/saltychat-redm#13]
Possible to let the Server decide for to use "whisper" or "mute/unmute"

It woould be nice to have the newest version with the possiblility to change what mode is desired.

If not would be sad but still okay, then i need to use a 2.X.X version.

**Comment by BlackFlash5** [comment]
It's a new major version for a reason.
Both models are incompatible between each other because the logic in the background is different.
With (un-)mute your local client needs to know which players you can hear to (un-)mute them and whisper is the opposite, the client needs to know which player can hear them to target them.
We currently have no plans to support both models in one version.
You also don't NEED to use 2.x.x, you can just read the docs and setup the whisper permissions on your ts server correctly.
